identifier: auth-service
title: Authentication Service
description: Handles user login, registration, and token issuance
owner: example_team
language: Python
lifecycle: production
tags:
  - auth
  - security
  - backend
relations:
  team:
    - identifier: example_team
